language: php

php:
  - 5.3

before_script:
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:phpcr:init:dbal
  - php app/console doctrine:phpcr:workspace:create standard_test
  - php app/console doctrine:phpcr:repository:init -e=test


script: phpunit -c app

notifications:
  email: "shiftorga@gmail.com"
